### ISSUE TITLE
Data should be a List<double>

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#20]
From the line chart example in the readme:

```csharp
Data = new List<int> { 4, 5, 6, 7 },
```

It should be (and it is in Chart.Js) possible to add double / float values to the chart data as well. So, in my opinion `Data` should be of type `List<double>`.

**Comment by Joelius300** [comment]
There is no line chart example in the readme but I guess you mean the pie chart example.  
You are correct that `double` would make more sense than `int`. As you know, I have only reworked `LineChart` at the moment. I will definitely change this to `double` if there isn't anything else which would be applied there.  

If you want you can open up an issue where we can discuss the priority of charts so we can choose which ones to rework next. Maybe even with a poll? I've never done something like that so go ahead if you have a suggestion.  
Currently I think I'll rework `BarChart` and `MixedChart` next since these have some similarities and relations with `LineChart`.  
If you're in need of `PieChart` feel free to either do some work on it directly, give it a high priority or open an issue with what you'd like to see changed about it.

**Comment by SeppPenner** [comment]
> There is no line chart example in the readme but I guess you mean the pie chart example.

You're right.

> Currently I think I'll rework BarChart and MixedChart next since these have some similarities and relations with LineChart.

This is a good idea. I will maybe take a look at the pie chart because it's the one I will need the most after the line chart at the moment.

I haven't used polls yet, but you might try https://github.com/apps/polls.

**Comment by SeppPenner** [comment]
This issue applies to other chart types as well. I will try to provide a pull request here.

**Comment by SeppPenner** [comment]
It's here: https://github.com/Joelius300/ChartJSBlazor/pull/23 (Contains other fixes for the doughnut chart as well).

**Comment by SeppPenner** [comment]
This will be fixed when the pull request is merged.
