### ISSUE TITLE
Create a (short) Contributing section in README.md and add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by MindSwipe** [Joelius300/ChartJSBlazor#24]
As this project isn't just one person doing it anymore we should create contributing guidelines including but not limited to

- The contribution process (how to contribute)
- A short explanation of the project architecture and the CI/CD pipeline
- A short summary of code style and conventions

Plus anything more you can think of

**Comment by SeppPenner** [comment]
Good idea.

**Comment by SeppPenner** [comment]
Maybe something similar to this? https://gist.github.com/PurpleBooth/b24679402957c63ec426 (Adjusted of course).

This one is better, I guess: https://gist.github.com/briandk/3d2e8b3ec8daf5a27a62

**Comment by Joelius300** [comment]
I agree that this is necessary now. I will add a file with the necessary stuff in it. However there isn't much really much to say. You can later expand that file if you find that there are some things missing.  

Regarding the CI/CD..  
I have not mastered the CI/CD pipeline yet and have not really an idea of how to use it correctly. Can you look at [this](https://github.com/Joelius300/ChartJSBlazor/pull/16) and [this](https://github.com/Joelius300/ChartJSBlazor/pull/17) azure PR if you know anything about this? I don't put much focus on that currently as I don't yet see the advantage for this project because we don't have any tests (yet?) and since I couldn't get the automatic nuget stuff (for delivery) to work.

**Comment by MindSwipe** [comment]
I created a somewhat short draft for CONTRIBUTING.md [here](https://gist.github.com/MindSwipe/c1793906eee7feaa643501edfbcac34a). Do you guys see anything wrong with it or feel like something is missing?

**Comment by SeppPenner** [comment]
Looks good for me. We should maybe as well think of issue templates. I have created some for another project I currently support: https://github.com/chkr1011/MQTTnet/tree/master/.github/ISSUE_TEMPLATE. It would be good to have something like this, too? What do you guys think?

**Comment by MindSwipe** [comment]
Issue templates are a great idea

**Comment by SeppPenner** [comment]
I have added these in https://github.com/Joelius300/ChartJSBlazor/pull/52.

**Comment by MindSwipe** [comment]
Ah great!

I feel like we could also use a "question.md" template for issues that are just a question

**Comment by SeppPenner** [comment]
Maybe I should rename `custom.md`. This is the one used for general questions.

**Comment by SeppPenner** [comment]
Looks good:

![image](https://user-images.githubusercontent.com/9639361/62775126-14a25b00-baa7-11e9-9265-2c2076c09d4a.png)
