### ISSUE TITLE
Rename the class DoughnutAnimation?

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#29]
In my opinion, we should rename `DoughnutAnimation` to something other. It is used in PieChart and DoughnutChart. Additionally, the only difference between both of them seems to be the type, correct? Maybe, we can build base classes here for more simplicity: https://www.chartjs.org/docs/latest/charts/doughnut.html

**Comment by SeppPenner** [comment]
Only difference at all:

>  Pie charts also have a clone of these defaults available to change at Chart.defaults.pie, with the only difference being cutoutPercentage being set to 0.

Meaning:

Pie: CutoutPercentage --> Default : 0
Doughnut: CutoutPercentage --> Default : 50

**Comment by Joelius300** [comment]
Correct.  
I've noticed this already but did not yet start to rework those (and hence didn't really decide on how to handle it).  

I suggest we remove everything `Doughnut` and only have `Pie` (or the other way around but I think `Pie` is more known than `Doughnut`).  

Then we have two options.  

### Optional bool parameter for options
We could then add an optional parameter of type `bool` to `PieChartOptions` named `isDoughnut`. It defaults to `false` of course. Depending on this bool we set the `CutoutPercentage` to `0` or to `50`.  
Nothing else would change (there wouldn't be a `DoughnutChartConfig`, you'd do it with `PieChartConfig`).

### Remove default value and keep DoughnutChartConfig
Since dougnut and pie are aliases in chart.js EXCEPT that they have a different default value for the cutout, we could also remove the default value of the cutout (type = `int?`, default = `null`). We'd need to keep the `DoughnutChartConfig` which specifies the correct type ("doughnut") though.  
This would result in the following: If not specified otherwise, the default value of the type would be used. This means you either use `DoughnutChartConfig` (every suboption of this config is `Pie`) and it defaults to 50 (in chart.js, not in our application) or you use `PieChartConfig` which chart.js will default to 0.


The first has the advantage that there isn't _any_ `Doughnut` stuff around anymore, so less confusion. The disadvantage is that the default value is set by our library, not by chart.js.  

The second has the advantage that chart.js chooses the default. It has the disadvantage that you have to use `DoughnutChartConfig` with `PieChartOptions` and `PieChartData` etc which might be confusing and doesn't look right.

I opt for the first one (optional parameter). What do you think/prefer?

**Comment by SeppPenner** [comment]
I was thinking of the second way to do this, too. But I agree with you, that this:

> It has the disadvantage that you have to use DoughnutChartConfig with PieChartOptions and PieChartData etc which might be confusing and doesn't look right.

really confuses people...

The first one seems to be legit (I don't see a real problem with that one if it's documented properly.)

**Comment by Joelius300** [comment]
> I don't see a real problem with that one if it's documented properly

Same. I think we should use this (optional bool parameter). Do you want to implement that since you've already reworked both `Pie` and `Doughnut` (rip) chart? I know that's just more commits on that already big PR but then we'd have less files so I think we should just do it there. I can review and merge it after you've deleted those.

**Comment by SeppPenner** [comment]
I would rather merge both pull requests https://github.com/Joelius300/ChartJSBlazor/pull/23 and https://github.com/Joelius300/ChartJSBlazor/pull/30 before and do this in a new branch? Or should I close https://github.com/Joelius300/ChartJSBlazor/pull/30 and put the new stuff and the changes from here to the big PR as you suggested?

I mean, it's not a problem, but the PR is really getting big :D

**Comment by SeppPenner** [comment]
This is now all in https://github.com/Joelius300/ChartJSBlazor/pull/23. It's fixed when this pull request is merged.
