### ISSUE TITLE
Read-only design of data

### ISSUE THREAD

**Issue by Venando-a** [Joelius300/ChartJSBlazor#32]
What is the reason behind the data property of ChartConfig and the data set property of data being "read-only" as they make the creation of charts unnecessarily complex? Further, why are labels not "read-only" even though they are part of the same data set?

**Comment by SeppPenner** [comment]
> What is the reason behind the data property of ChartConfig and the data set property of data being "read-only" as they make the creation of charts unnecessarily complex?

To be honest, I disagree that this is more complicated...

> Further, why are labels not "read-only" even though they are part of the same data set?

Well, because the library still is inconsistent as hell...

**Comment by Joelius300** [comment]
I'll try to explain this.  

### Data of dataset

The first reason I started doing so was because data is always required for a dataset. Not only does it not make sense to have no data, it will also break chart.js.  
Since you can still add, remove and modify the data in any way you'd like, it makes a lot more sense to just expose a getter.  
This is also a property which is not static in most cases (the values are dynamically added from somewhere) so it doesn't really make sense to allow this to be initialized with the normal property-initializer.

The second reason is covariance in the `IMixableDataset` (currently used for `LineChart` but this will probably expand. Or not if we can settle on a better solution). You've already come across the wrappers I implemented. This is only done because we need the covariance to be able to have multiple datasets which contain different types in one chart (that's why the `Datasets` property is of type `_Collection<IMixableDataset<object>>` instead of `_Collection<LineChartDataset>`).  
Primative types don't work for covariance that's why we need the wrappers.  
Another thing that's not allowed if you use covariance is being mutable. Since you can assign `IMixableDataset<string>` to `IMixableDataset<object>` you need to disallow adding new data to this since you could add any `object` to `IMixableDataset<object>` even when it actually was `IMixableDataset<string>` before reassigning it (there was no cast!).  

### Data of config

Again, it doesn't make sense to have a chart without data. 


### Unnecessarily complex

Since you need to get a reference to your dataset anyway to add data, you can add this to the data-suboptions of your chart-config without any issues.  
Initializing with the property-initializer (the tree structure) is great for static content. However for data this doesn't really make sense. You can still use the property-initializer for the static content inside each dataset etc, you just can't use it in the big config where all the static content is. This also keeps everything more organized since you separate static from dynamic content (of course both can be either one but in general the options are static and the data is dynamic).

### Why are not all labels readonly

As @SeppPenner mentionend: 

> Well, because the library still is inconsistent as hell...

This is of course true since we didn't rework all the charts yet.  

There is however another very important reason.  
Not all charts require labels but some do. A `PieChart` without labels doesn't make sense because then it's not determined what this part of the pie is.  
On the other hand, you have charts like `LineChart` where it is possible to use labels if you use a `CategoryAxis` along with it. It's not required however and if we were to make it required, we would break the chart.

Closing this for now. If you have any other questions regarding this, you can reopen it. If it's not directly about this, you're better off opening a new issue.
