### ISSUE TITLE
Make a nuget package out of this library

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#4]
The original project has provided a nuget package. It would be appreciated if you could publish one, too.

**Comment by Joelius300** [comment]
Do you think it's appropriate to do that in the current state? There are some things I want to change (e.g. static content of the library) and the library is definitely not complete yet.

**Comment by SeppPenner** [comment]
Well, you can make the current state something like a `0.x-preview` as well and update the package afterwards to a stable or release version. I believe that more people will find the library if it's on nuget and it eventually might get more users to test it.

**Comment by SeppPenner** [comment]
Additionally: Add the package link to the readme (There is a todo in it).

**Comment by SeppPenner** [comment]
I have added the option to generate the package on build here: https://github.com/Joelius300/ChartJSBlazor/pull/11/commits/067878699236f4eccdd8e5409cc53f0692d55697. Afterwards, you can easily upload the file to nuget.org and add the links to the readme. For me, it would be a great benefit because I want to use this library extensively (and don't want to clone, build and push it to a custom nuget server everytime you change something...)

**Comment by Joelius300** [comment]
I have created an azure pipeline etc. I'm _very_ new to this so please tell me if I'm doing something wrong.  
I will use the pipeline to also pack and upload the nuget. I'm currently struggling to get it to work.  

Also do you have an idea for the name? [ChartJs.Blazor](https://www.nuget.org/packages/ChartJs.Blazor) is of course already in use and since you can install it just with the name `ChartJs.Blazor` I think this package needs to have a different name.  
Should I just do `ChartJs.Blazor.Joelius` or something like that? Is there a standard way for doing this?  

Also another important thing is the version. Do you think we should continue at 0.9.1? It feels like this is very close to 1.0.0 which would take it out of beta (I guess) and I don't want to signal that just yet. We could also go higher say 0.10.1 and up, before going to 1.0.0.  

@SeppPenner, Please tell me your ideas and suggestions on that :)

**Comment by Joelius300** [comment]
I have now created a nuget package on nuget.org. You can find it [here](https://www.nuget.org/packages/ChartJs.Blazor.Fork/). I have also updated the ReadMe. See [this commit](https://github.com/Joelius300/ChartJSBlazor/commit/e2654e2f90d8166d050e02e9c71c23529c17e82f).  

Automatic packing/pushing with azure pipelines is still possible (and will probably be done in the future). Relevant links for that are currently:
 - [SO answer for versioning etc](https://stackoverflow.com/questions/54718866/azure-pipeline-nuget-package-versioning-scheme-how-to-get-1-0-revr/56111209#56111209)
- [DevOps project](https://dev.azure.com/joelius300/ChartJs.Blazor)
- [Pull request](https://github.com/Joelius300/ChartJSBlazor/pull/17) where this was attempted.

If you have anything to add or want me to change something (e.g. I did something terribly wrong) just comment on here.

**Comment by SeppPenner** [comment]
Sorry for the late reply. I haven't setup a package build using `azure pipeline` yet...

There is no naming convention, I guess... I would use something like `.Fork` or `.New` or whatever to indicate that it's the same library but provides more and new features (and bugfixes).

Sure, `0.10.1` is a good idea :)

It looks really good. I will try it and reply here if there is something wrong. At the moment, I don't see anything though ;)
