### ISSUE TITLE
Enum class names should be consistently singular

### ISSUE THREAD

**Issue by SeppPenner** [Joelius300/ChartJSBlazor#85]
Currently, we have the following:

![image](https://user-images.githubusercontent.com/9639361/64944533-d7cc3f80-d86e-11e9-99c1-ec1569f64fa3.png)

Should enum class names be singular or plural? (There is just one (`ChartTypes`) that is plural) at the moment. (`PointStyles` is the one I'm currently working on).

**Comment by Joelius300** [comment]
It should be singular. You can rename `ChartTypes` to `ChartType`, it shouldn't have any consequences outside of the library as far as I'm concerned. `PointStyles` is new so you can rename it without consequences.

You missed two more though:
- `Positions` should be renamed to `Position`.
- `ScaleBounds` should be renamed to `ScaleBound` since bound does make sense here even though it kind of sounds wrong in my foreign ears :)

**Comment by SeppPenner** [comment]
I already thought that there were some more and I only didn't see them in the screenshot.

`PointStyles` is already renamed, I will do the others within the special enum branch.

**Comment by SeppPenner** [comment]
Is fixed in https://github.com/Joelius300/ChartJSBlazor/issues/87.

**Comment by SeppPenner** [comment]
I guess this can be closed as well.
